In [1]:
import pandas as pd

In [ ]:
data = pd.read_csv("data/raw/hr_dashboard_data.csv")
data.head()

,Name,Age,Gender,Projects Completed,Productivity (%),Satisfaction Rate (%),Feedback Score,Department,Position,Joining Date,Salary
0,Douglas Lindsey,25,Male,11,57,25,4.7,Marketing,Analyst,Jan-20,63596
1,Anthony Roberson,59,Female,19,55,76,2.8,IT,Manager,Jan-99,112540
2,Thomas Miller,30,Male,8,87,10,2.4,IT,Analyst,Jan-17,66292
3,Joshua Lewis,26,Female,1,53,4,1.4,Marketing,Intern,Jan-22,38303
4,Stephanie Bailey,43,Male,14,3,9,4.5,IT,Team Lead,Jan-05,101133

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name                   200 non-null    object
 1   Age                    200 non-null    int64
 2   Gender                 200 non-null    object
 3   Projects Completed     200 non-null    int64
 4   Productivity (%)       200 non-null    int64
 5   Satisfaction Rate (%)  200 non-null    int64
 6   Feedback Score         200 non-null    float64
 7   Department             200 non-null    object
 8   Position               200 non-null    object
 9   Joining Date           200 non-null    object
 10  Salary                 200 non-null    int64
dtypes: float64(1), int64(5), object(5)
memory usage: 17.3+ KB

In [4]:
data["Joining Date"]

0      Jan-20
1      Jan-99
2      Jan-17
3      Jan-22
4      Jan-05
        ...
195    Jan-19
196    Jan-21
197    Jan-21
198    Jan-05
199    Jan-14
Name: Joining Date, Length: 200, dtype: object

In [9]:
data_date = data.copy()
data_date['Joining Date'] = pd.to_datetime(data_date['Joining Date'], format='%b-%y')

In [10]:
data_date.head()

,Name,Age,Gender,Projects Completed,Productivity (%),Satisfaction Rate (%),Feedback Score,Department,Position,Joining Date,Salary
0,Douglas Lindsey,25,Male,11,57,25,4.7,Marketing,Analyst,2020-01-01,63596
1,Anthony Roberson,59,Female,19,55,76,2.8,IT,Manager,1999-01-01,112540
2,Thomas Miller,30,Male,8,87,10,2.4,IT,Analyst,2017-01-01,66292
3,Joshua Lewis,26,Female,1,53,4,1.4,Marketing,Intern,2022-01-01,38303
4,Stephanie Bailey,43,Male,14,3,9,4.5,IT,Team Lead,2005-01-01,101133

In [12]:
data_date["Joining Date"].value_counts().sort_index()

Joining Date
1998-01-01     1
1999-01-01     4
2000-01-01     2
2001-01-01     2
2002-01-01     1
2003-01-01     6
2004-01-01     6
2005-01-01    10
2006-01-01     6
2007-01-01     9
2008-01-01     5
2009-01-01     6
2010-01-01     6
2011-01-01     5
2012-01-01     3
2013-01-01    10
2014-01-01     5
2015-01-01     3
2016-01-01     7
2017-01-01     8
2018-01-01    23
2019-01-01    20
2020-01-01    19
2021-01-01    21
2022-01-01    12
Name: count, dtype: int64

In [13]:
data_salary = data_date.copy()
data_salary["Salary"].isnull().sum()

np.int64(0)

In [16]:
data_salary["Salary"] = data_salary["Salary"].fillna(data_salary["Salary"].median())
data_salary.info

<bound method DataFrame.info of                   Name  Age  Gender  Projects Completed  Productivity (%)  \
0      Douglas Lindsey   25    Male                  11                57
1     Anthony Roberson   59  Female                  19                55
2        Thomas Miller   30    Male                   8                87
3         Joshua Lewis   26  Female                   1                53
4     Stephanie Bailey   43    Male                  14                 3
..                 ...  ...     ...                 ...               ...
195   Stephanie Fisher   29  Female                   9                32
196      Jeremy Miller   26    Male                   7                45
197      Daniel Pierce   22    Male                   3                36
198  Michael Hernandez   36  Female                  23                96
199   Victor Gutierrez   43    Male                  10                86

     Satisfaction Rate (%)  Feedback Score Department          Position  \
0                       25             4.7  Marketing           Analyst
1                       76             2.8         IT           Manager
2                       10             2.4         IT           Analyst
3                        4             1.4  Marketing            Intern
4                        9             4.5         IT         Team Lead
..                     ...             ...        ...               ...
195                     87             3.5         HR  Junior Developer
196                     28             2.8         IT  Junior Developer
197                     77             1.6    Finance            Intern
198                     50             3.4  Marketing           Manager
199                     71             2.0         IT         Team Lead

    Joining Date  Salary
0     2020-01-01   63596
1     1999-01-01  112540
2     2017-01-01   66292
3     2022-01-01   38303
4     2005-01-01  101133
..           ...     ...
195   2019-01-01   50051
196   2021-01-01   46612
197   2021-01-01   32992
198   2005-01-01  104216
199   2014-01-01  104341

[200 rows x 11 columns]>

In [17]:
data_salary.head()

,Name,Age,Gender,Projects Completed,Productivity (%),Satisfaction Rate (%),Feedback Score,Department,Position,Joining Date,Salary
0,Douglas Lindsey,25,Male,11,57,25,4.7,Marketing,Analyst,2020-01-01,63596
1,Anthony Roberson,59,Female,19,55,76,2.8,IT,Manager,1999-01-01,112540
2,Thomas Miller,30,Male,8,87,10,2.4,IT,Analyst,2017-01-01,66292
3,Joshua Lewis,26,Female,1,53,4,1.4,Marketing,Intern,2022-01-01,38303
4,Stephanie Bailey,43,Male,14,3,9,4.5,IT,Team Lead,2005-01-01,101133

In [18]:
data_dup = data_salary.copy()
data_dup = data_dup.drop_duplicates(subset="Name")
data_dup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name                   200 non-null    object
 1   Age                    200 non-null    int64
 2   Gender                 200 non-null    object
 3   Projects Completed     200 non-null    int64
 4   Productivity (%)       200 non-null    int64
 5   Satisfaction Rate (%)  200 non-null    int64
 6   Feedback Score         200 non-null    float64
 7   Department             200 non-null    object
 8   Position               200 non-null    object
 9   Joining Date           200 non-null    datetime64[ns]
 10  Salary                 200 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(5), object(4)
memory usage: 17.3+ KB

In [22]:
# Experience Years (từ Joining Date đến hiện tại)
data_year = data_salary.copy()

today = pd.Timestamp.today()
today

Timestamp('2026-03-24 13:27:45.912716')

In [23]:
data_year['Experience Years'] = (today - data_year['Joining Date']).dt.days / 365
data_year['Experience Years'] = data_year['Experience Years'].round(0)

In [25]:
data_year["Experience Years"].value_counts().sort_index()

Experience Years
4.0     12
5.0     21
6.0     19
7.0     20
8.0     23
9.0      8
10.0     7
11.0     3
12.0     5
13.0    10
14.0     3
15.0     5
16.0     6
17.0     6
18.0     5
19.0     9
20.0     6
21.0    10
22.0     6
23.0     6
24.0     1
25.0     2
26.0     2
27.0     4
28.0     1
Name: count, dtype: int64

In [24]:
data_year.head()

,Name,Age,Gender,Projects Completed,Productivity (%),Satisfaction Rate (%),Feedback Score,Department,Position,Joining Date,Salary,Experience Years
0,Douglas Lindsey,25,Male,11,57,25,4.7,Marketing,Analyst,2020-01-01,63596,6.0
1,Anthony Roberson,59,Female,19,55,76,2.8,IT,Manager,1999-01-01,112540,27.0
2,Thomas Miller,30,Male,8,87,10,2.4,IT,Analyst,2017-01-01,66292,9.0
3,Joshua Lewis,26,Female,1,53,4,1.4,Marketing,Intern,2022-01-01,38303,4.0
4,Stephanie Bailey,43,Male,14,3,9,4.5,IT,Team Lead,2005-01-01,101133,21.0

In [28]:
# Productivity Group (Low: <50%, Medium: 50-80%, High: >80%)
data_product = data_year.copy()

# hàm product 
def productivity_group(product):
    if product < 50:
        return "Low"
    elif 50 <= product <= 80:
        return "Medium"
    else:
        return "High"

data_product["Productivity Group"] = data_product["Productivity (%)"].apply(productivity_group)

In [29]:
data_product.head(10)

,Name,Age,Gender,Projects Completed,Productivity (%),Satisfaction Rate (%),Feedback Score,Department,Position,Joining Date,Salary,Experience Years,Productivity Group
0,Douglas Lindsey,25,Male,11,57,25,4.7,Marketing,Analyst,2020-01-01,63596,6.0,Medium
1,Anthony Roberson,59,Female,19,55,76,2.8,IT,Manager,1999-01-01,112540,27.0,Medium
2,Thomas Miller,30,Male,8,87,10,2.4,IT,Analyst,2017-01-01,66292,9.0,High
3,Joshua Lewis,26,Female,1,53,4,1.4,Marketing,Intern,2022-01-01,38303,4.0,Medium
4,Stephanie Bailey,43,Male,14,3,9,4.5,IT,Team Lead,2005-01-01,101133,21.0,Low
5,Jonathan King,24,Male,5,63,33,4.2,Sales,Junior Developer,2021-01-01,48740,5.0,Medium
6,Kyle Figueroa,33,Female,13,41,39,2.3,Sales,Analyst,2018-01-01,73502,8.0,Low
7,Shannon Allen,23,Female,4,92,68,2.8,HR,Intern,2021-01-01,39670,5.0,High
8,Daryl Noble,30,Female,7,32,43,2.3,Marketing,Junior Developer,2019-01-01,49323,7.0,Low
9,Tracy Figueroa,39,Female,17,10,15,1.1,HR,Team Lead,2004-01-01,92915,22.0,Low

In [ ]:
data_product.to_csv("data/processed/hr_dashboard_data_clean.csv")